# Generated by Django 6.0.1 on 2026-01-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fooddelivery',
            fields=[
                ('name', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=25)),
                ('order', models.CharField(max_length=15)),
                ('money', models.FloatField()),
                ('mobile_no', models.IntegerField()),
            ],
        ),
    ]
